# This compose file overrides 'docker-compose.base.yml'.
services:
  eutardigrada-server:
    container_name: ${DEV_CONTAINER_NAME}
    build: .
    environment:
      DEFAULT_SERVER_DOMAIN: Eutardigrada.YOCKOW.test
      HOST_HTTP_PORT: "${DEV_HTTP_PORT}"
      HOST_HTTPS_PORT: "${DEV_HTTPS_PORT}"
    volumes:
      - type: bind
        read_only: true
        source: "${HOST_ROOT_DIR}/.certs"
        target: "/certs"
    ports:
      - "${DEV_HTTP_PORT}:80"
      - "${DEV_HTTPS_PORT}:443"
    command: >-
      httpd -f /home/swifche/Web/Config/httpd.conf -DEUTARDIGRADA_TEST
