# This compose file overrides 'docker-compose.base.yml'.
networks:
  eutardigrada-network:
    ipam:
      config:
        - subnet: "172.20.90.0/24"
services:
  eutardigrada-server:
    container_name: ${PROD_CONTAINER_NAME}
    image: ghcr.io/yockow/eutardigrada.yockow.jp:latest
    restart: unless-stopped
    environment:
      DEFAULT_SERVER_DOMAIN: Eutardigrada.YOCKOW.jp
      HOST_HTTP_PORT: "80"
      HOST_HTTPS_PORT: "443"
    volumes:
      - type: bind
        read_only: true
        source: /etc/letsencrypt
        target: /certs
    networks:
      eutardigrada-network:
        ipv4_address: "172.20.90.64"
    ports:
      - "127.0.90.64:${PROD_HTTP_PORT}:80"
      - "127.0.90.64:${PROD_HTTPS_PORT}:443"
    command: >-
      httpd -f /home/swifche/Web/Config/httpd.conf
