# Supposed to be overridden by another file.
services:
  eutardigrada-server:
    environment:
      TZ: Asia/Tokyo
      WWW_GROUP_ID: ${WWW_GROUP_ID}
    volumes:
      - type: bind
        source: ${HOST_WEB_SHARED_DIR}
        target: /home/swifche/Web/shared
