# This compose file overrides 'docker-compose.base.yml'.
networks:
  eutardigrada-network:
    name: eutardigrada-network
    ipam:
      config:
        - subnet: "${PROD_NETWORK_IP_RANGE}"
services:
  eutardigrada-server:
    container_name: ${PROD_CONTAINER_NAME}
    image: ghcr.io/yockow/eutardigrada.yockow.jp:latest
    restart: unless-stopped
    environment:
      DEFAULT_SERVER_DOMAIN: Eutardigrada.YOCKOW.jp
      HOST_HTTP_PORT: "80"
      HOST_HTTPS_PORT: "443"
    volumes:
      - type: bind
        read_only: true
        source: /etc/letsencrypt
        target: /certs
    networks:
      eutardigrada-network:
        ipv4_address: "${PROD_HTTP_SERVER_IPV4_ADDRESS}"
    ports:
      - "${PROD_HTTP_SERVER_LOOPBACK_ADDRESS}:${PROD_HTTP_PORT}:80"
      - "${PROD_HTTP_SERVER_LOOPBACK_ADDRESS}:${PROD_HTTPS_PORT}:443"
    command: >-
      httpd -f /home/swifche/Web/Config/httpd.conf
