# This compose file overrides 'docker-compose.base.yml'.
services:
  eutardigrada-server:
    container_name: ${PROD_CONTAINER_NAME}
    image: ghcr.io/yockow/eutardigrada.yockow.jp:latest
    restart: unless-stopped
    environment:
      DEFAULT_SERVER_DOMAIN: Eutardigrada.YOCKOW.jp
      HOST_HTTP_PORT: ${PROD_HTTP_PORT}
      HOST_HTTPS_PORT: ${PROD_HTTPS_PORT}
    volumes:
      - type: bind
        read_only: true
        source: /etc/letsencrypt
        target: /certs
    ports:
      - "${PROD_HTTP_PORT}:80"
      - "${PROD_HTTPS_PORT}:443"
    command: >-
      httpd -f /home/swifche/Web/Config/httpd.conf
