name: Deploy Eutardigrada.YOCKOW.jp
on:
  workflow_run:
    workflows:
      - Test Eutardigrada.YOCKOW.jp
    types:
      - completed
    branches:
      - main
  push:
    tags:
      - "release-*"
permissions:
  packages: write
  contents: read
  attestations: write
  id-token: write
jobs:
  Define-Constants:
    if: >-
      ${{
        github.event_name == 'push' || (
          github.event_name == 'workflow_run' &&
          github.event.workflow_run.conclusion == 'success'
        )
      }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repository
        uses: actions/checkout@v4
      - name: Get Build Args
        id: get-build-args
        run: |
          echo "swift-version=$(cat .swift-version)" >>"$GITHUB_OUTPUT"
          echo "os-nickname=$(cat .swift-build-os)" >>"$GITHUB_OUTPUT"
      - name: Define Tag Name
        id: define-tag-name
        env:
          REF_TYPE: ${{ github.ref_type }}
          REF_NAME: ${{ github.ref_name }}
        run: |
          case "$REF_TYPE" in
          branch)
            if [[ "$REF_NAME" == "main" ]]; then
              echo "tag_name=latest" >>"$GITHUB_OUTPUT"
            fi
          ;;
          tag)
            if [[ "$REF_NAME" == release-* ]]; then
              echo "tag_name=$REF_NAME" >>"$GITHUB_OUTPUT"
            fi
          ;;
          *)
            echo "tag_name=" >>"$GITHUB_OUTPUT"
          ;;
          esac
      - name: Calculate Hash
        id: calculate-hash
        env:
          SWIFT_FILES_HASH: ${{ hashFiles('CGISources/**/*.swift') }}
        run: |
          echo "swift-files-hash=${SWIFT_FILES_HASH}" >>"$GITHUB_OUTPUT"
    outputs:
      swift-version: ${{ steps.get-build-args.outputs.swift-version }}
      os-nickname: ${{ steps.get-build-args.outputs.os-nickname }}
      tag-name: ${{ steps.define-tag-name.outputs.tag_name }}
      swift-files-hash: ${{ steps.calculate-hash.outputs.swift-files-hash }}
  Deploy:
    needs:
      - Define-Constants
    uses: YOCKOW/DockerSwiftApacheCombination/.github/workflows/reusable_build-multiplatform-image.yml@main
    with:
      if-absent: false
      build-args: |
        SWIFT_VERSION=${{ needs.Define-Constants.outputs.swift-version }}
        OS_NICKNAME=${{ needs.Define-Constants.outputs.os-nickname }}
      registry: ghcr.io
      username: ${{ github.actor }}
      image-basename: eutardigrada.yockow.jp
      tags: ${{ needs.Define-Constants.outputs.tag-name }}
      cache-file-path: .swift-scratch
      cache-file-key-suffix: ${{ needs.Define-Constants.outputs.os-nickname }}-${{ needs.Define-Constants.outputs.swift-version }}-${{ needs.Define-Constants.outputs.swift-files-hash }}
      set-up-command: >-
        sudo apt update &&
        sudo apt install zsh &&
        ./utils/swift-pre-build --configuration debug &&
        ./utils/swift-pre-build --configuration debug --test &&
        ./utils/swift-pre-build --configuration release
      push: true
    secrets:
      password: ${{ secrets.GITHUB_TOKEN }}
