name: Deploy Eutardigrada.YOCKOW.jp
on:
  push:
    branches:
      - main
    tags:
      - "release-*"
permissions:
  packages: write
  contents: read
  attestations: write
  id-token: write
jobs:
  Define-Constants:
    runs-on: ubuntu-latest
    steps:
      - name: Define Tag Name
        id: define-tag-name
        env:
          REF_TYPE: ${{ github.ref_type }}
          REF_NAME: ${{ github.ref_name }}
        run: |
          case "$REF_TYPE" in
          branch)
            if [[ "$REF_NAME" == "main" ]]; then
              echo "tag_name=latest" >>"$GITHUB_OUTPUT"
            fi
          ;;
          tag)
            if [[ "$REF_NAME" == release-* ]]; then
              echo "tag_name=$REF_NAME" >>"$GITHUB_OUTPUT"
            fi
          ;;
          *)
            echo "tag_name=" >>"$GITHUB_OUTPUT"
          ;;
          esac
    outputs:
      tag-name: ${{ steps.define-tag-name.outputs.tag_name }}
  Deploy:
    needs:
      - Define-Constants
    uses: YOCKOW/DockerSwiftApacheCombination/.github/workflows/reusable_build-multiplatform-image.yml@main
    with:
      if-absent: false
      registry: ghcr.io
      username: ${{ github.actor }}
      image-basename: eutardigrada.yockow.jp
      tags: ${{ needs.Define-Constants.outputs.tag-name }}
      push: true
    secrets:
      password: ${{ secrets.GITHUB_TOKEN }}
