name: Deploy Eutardigrada.YOCKOW.jp
on:
  push:
    branches:
      - main
    tags:
      - "release-*"
permissions:
  packages: write
  contents: read
  attestations: write
  id-token: write
jobs:
  Deploy:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
    steps:
      - name: Define Tag Name
        id: define-tag-name
        env:
          REF_TYPE: ${{ github.ref_type }}
          REF_NAME: ${{ github.ref_name }}
        run: |
          case "$REF_TYPE" in
          branch)
            if [[ "$REF_NAME" == "main" ]]; then
              echo "tag_name=latest" >>"$GITHUB_OUTPUT"
            fi
          ;;
          tag)
            if [[ "$REF_NAME" == release-* ]]; then
              echo "tag_name=$REF_NAME" >>"$GITHUB_OUTPUT"
            fi
          ;;
          *)
            echo "tag_name=" >>"$GITHUB_OUTPUT"
          ;;
          esac
      - name: Check out Repository
        uses: actions/checkout@v4
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Metadata
        id: extract-metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          tags: type=raw,value=${{ steps.define-tag-name.outputs.tag_name }}
      - name: Build and Push the image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.extract-metadata.outputs.tags }}
          labels: ${{ steps.extract-metadata.outputs.labels }}
