name: Test Eutardigrada.YOCKOW.jp
on:
  push:
    branches:
      - "*"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repository
        uses: actions/checkout@v4
      - name: Install dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install zsh
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
      - name: Test
        env:
          TEST_HTTP_PORT: "80"
          TEST_HTTPS_PORT: "443"
          TEST_SERVER_DOMAIN: eutardigrada.yockow.test
        run: |
          set -eu
          {
            sudo groupadd swifche
            sudo gpasswd --add $(whoami) swifche
            ./utils/generate-development-certificates
            ./utils/start-development-server
            curl -v --retry 5 --retry-delay 2 --retry-all-errors localhost:$TEST_HTTP_PORT
            curl -v --fail-with-body --http2 --cacert .certs/ca/dev-ca.crt --resolve ${TEST_SERVER_DOMAIN}:${TEST_HTTPS_PORT}:127.0.0.1 https://${TEST_SERVER_DOMAIN}:${TEST_HTTPS_PORT}
            ./utils/stop-development-server
          } 2>&1
